name: Build Project

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
        arch: [x86_64, arm64]
        exclude:
          # macOS only supports arm64 on Apple Silicon
          - os: macos-latest
            arch: x86_64
    runs-on: ${{ matrix.os }}-${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install build tools
        if: matrix.os == 'ubuntu-24.04'
        run: sudo apt-get update && sudo apt-get install -y cmake libsdl2-dev libcurl4-openssl-dev autoconf automake libtool autoconf-archive libltdl-dev

      - name: Install build tools (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install cmake sdl2 curl autoconf automake libtool

      - name: Build project
        run: make simulator

      - name: Package build artifacts
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            cd build && zip -r ../dist/lvgljs-macos-${{ matrix.arch }}.zip .
          elif [ "${{ matrix.os }}" = "ubuntu-24.04" ]; then
            cd build && zip -r ../dist/lvgljs-linux-${{ matrix.arch }}.zip .
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lvgljs-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            artifacts/lvgljs-macos-arm64/lvgljs-macos-arm64.zip
            artifacts/lvgljs-ubuntu-24.04-x86_64/lvgljs-linux-x86_64.zip
            artifacts/lvgljs-ubuntu-24.04-arm64/lvgljs-linux-arm64.zip